version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - .:/var/www/html
    networks:
      - default
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - default
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - default
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - default
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    command:
      - '-nginx.scrape-uri=http://nginx/nginx_status'
    ports:
      - '9113:9113'
    depends_on:
      - web
    networks:
      - default
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    command:
      - '--config.my-cnf=/etc/.my.cnf'
    volumes:
      - ./my.cnf:/etc/.my.cnf
    environment:
        - DATA_SOURCE_NAME=admin:password@(db:3306)/db
    ports:
      - '9104:9104'
    depends_on:
      - db
    networks:
      - default
volumes:
  db_data: {}
  grafana_storage: {}
networks:
  default:
    name: app
