global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
